# Generated by Django 5.1 on 2024-08-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jwt_signing_key',
            field=models.TextField(default=''),
        ),
    ]
